version: '3.0'

services:
  mysql:
    container_name: mysql
    build:
      context: db
      dockerfile: Dockerfile
    image: simplebefe/mysql:1.0.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root

  be:
    container_name: be
    build:
      context: api
      dockerfile: Dockerfile
    image: simplebefe/api:1.0.0
    restart: always
    depends_on:
      - mysql
