#!/bin/bash

cd /var/www/html
eval `ssh-agent`
ssh-add /var/tmp/.ssh/id_rsa

while :
do
	if [ ! -d .git ]
	then
		#ssh-agent $(ssh-add /var/tmp/.ssh/id_rsa; git clone git@bitbucket.org:stevshil/tpswww.git .)
		git clone git@bitbucket.org:stevshil/tpswww.git .
	else
		#ssh-agent $(ssh-add /var/tmp/.ssh/id_rsa; git pull)
		git pull
	fi
	sleep 3600
done
