FROM httpd:2.4
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY htaccess /usr/local/apache2/htdocs/.htaccess
#COPY index.html /usr/local/apache2/htdocs/index.html
#COPY my.mp3 /usr/local/apache2/htdocs/a.mp3
VOLUME /usr/local/apache2/htdocs
