version: "3"
services:
  app:
    image: steve353/unison
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home:/home
#    network_mode: host
