version: "3"
services:
  unison:
    image: steve353/unison
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - UNISONDIR=/home/steve
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home:/home
#    network_mode: host
