version: "3.0"
services:
  unison:
    image: steve353/unison
    build: .
    hostname: unison1
    container_name: unison1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home:/home
#    network_mode: host
