version: "3"
services:
  mysql:
    image: mysql:5.7.19
    container_name: mysql
    volumes:
      - "/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
  petclinic:
    build:
      context: .
      dockerfile: pcbuildcompile.dockerfile
    image: petclinic
    container_name: petclinic
    ports:
      - 1080:8080
    environment:
      - DBSERVERNAME=mysql
      - DBUSERNAME=root
      - DBPASSWORD=petclinic
