apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: petclinic
  name: petclinic
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: petclinic
    spec:
      containers:
      - env:
        - name: DBPASSWORD
          value: petclinic
        - name: DBSERVERNAME
          value: mysql
        - name: DBUSERNAME
          value: root
        image: petclinic
        name: petclinic
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
