global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'petclinic'
    # scrape_interval: 5s
    static_configs:
      - targets: ['petclinic:9100','petclinic:9995','petclinic:9256']
        labels:
          group: 'petclinic'

  - job_name: 'moodle'
    # scrape_interval: 5s
    static_configs:
      - targets: ['moodle:9100','moodle:9995','moodle:9256']
        labels:
          group: 'moodle'

  - job_name: 'Database'
    static_configs:
      # 9104 = mysqld_exporter, 9256 Process exporter, 9995 disk exporter, 9100 node
      - targets: ['dbmon:9104','database:9995','database:9100','database:9256']
        labels:
          group: 'database'
