global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'petclinic'
    # scrape_interval: 5s
    static_configs:
      - targets: ['petclinic:9100','petclinic:9995']
        labels:
          group: 'petclinic'

  - job_name: 'Database'
    static_configs:
      - targets: ['dbmon:9104','database:9995','database:9100']
        labels:
          group: 'database'
