version: '3'

services:
  auto-trader-mysql:
    container_name: auto-trader-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: tp-auto-trader/auto-trader-mysql:0.0.1
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --explicit_defaults_for_timestamp

  activemq:
    container_name: activemq
    build:
      context: .
      dockerfile: Dockerfile-activemq
    image: tp-auto-trader/activemq:0.0.1
    ports:
      - "8161:8161"
      - "61616:61616"
    restart: unless-stopped

  auto-trader-app:
    container_name: auto-trader-app
    build:
      context: .
      dockerfile: Dockerfile-app
    image: tp-auto-trader/auto-trader-app:0.0.1
    links:
      - auto-trader-mysql:auto-trader-mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: auto-trader-mysql
      DB_USER: root
      DB_PASS: root
      SERVER_PORT: 8080
    restart: unless-stopped
