version: "3.7"
services:
  mysql:
    image: mysql:5.7.19
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpapp
      - MYSQL_PASSWORD=secret123
    volumes:
      - my-datavolume:/var/lib/mysql
  wordpress:
    image: wordpress:php7.4-apache
    container_name: wordpress
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wpapp
      - WORDPRESS_DB_PASSWORD=secret123
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
volumes:
  my-datavolume:
