{
 "title": "Docker System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Container States",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers"
    }
   ]
  },
  {
   "title": "Container Actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_count"
    }
   ]
  },
  {
   "title": "Event Subscribers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_events_subscribers_total"
    }
   ]
  }
 ]
}