- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Add Prometheus node_exporter dashboard
    community.grafana.grafana_dashboard:
      grafana_url: http://localhost:3000
      url_username: admin
      url_password: "{{ lookup('env', 'ADMIN_PW') }}"
      dashboard_id: "1860"
      dashboard_revision: "22"
      overwrite: yes
      state: present
      # folder: Prometheus
      #path: /tmp/prometheus-2-0-overview_rev2.json
      # dashboard_url: https://grafana.com/api/dashboards/3662/revisions/2/download
    
  - name: Add Docker and Host dashboard
    community.grafana.grafana_dashboard:
      grafana_url: http://localhost:3000
      url_username: admin
      url_password: "{{ lookup('env', 'ADMIN_PW') }}"
      dashboard_id: "179"
      dashboard_revision: "7"
      overwrite: yes
      state: present
    
  # - name: Add MySQL dashboard
  #   community.grafana.grafana_dashboard:
  #     grafana_url: http://localhost:3000
  #     url_username: admin
  #     url_password: "{{grafana_admin_password}}"
  #     dashboard_id: "6239"
  #     dashboard_revision: "1"
  #     overwrite: yes
  #     state: present
  #   notify: Restart Grafana
  - name: Upload MySQL dashboard
    copy:
      src: MySQLPrometheus.json
      dest: /tmp/MySQLPrometheus.json
  
  - name: Add MySQL dashboard
    community.grafana.grafana_dashboard:
      grafana_url: http://localhost:3000
      url_username: admin
      url_password: "{{ lookup('env', 'ADMIN_PW') }}"
      overwrite: yes
      state: present
      path: /tmp/MySQLPrometheus.json
  
  - name: Upload Simple Docker dashboard
    copy:
      src: DockerSystem.json
      dest: /tmp/DockerSystem.json
  
  - name: Simple Docker dashboard
    community.grafana.grafana_dashboard:
      grafana_url: http://localhost:3000
      url_username: admin
      url_password: "{{ lookup('env', 'ADMIN_PW') }}"
      overwrite: yes
      state: present
      path: /tmp/DockerSystem.json

# https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards
